### ISSUE TITLE
Add division operator

### ISSUE THREAD

**Issue by dgazzoni** [nestordemeure/pairArithmetic#1]
I came across this paper and associated library, and would like to try it on an application of mine, however I need divisions. As stated in the README:

> **Note**: our numbers implement additions and multiplications (and the associated in-place operations) but not divisions. Do not hesitate to add an issue if you need this operation as it would be easy to fix.

If it's indeed an easy fix, it would please me very much if you could add divisions to the library. Thank you in advance.

**Comment by nestordemeure** [comment]
I am a bit busy this week but it should be easy to add. I will try and to it before Monday.

**Comment by dgazzoni** [comment]
Thank you very much.

**Comment by nestordemeure** [comment]
Hi @dgazzoni, I just pushed support for the division operator! The code should be semantically correct (it draws on my [Shaman](https://gitlab.com/numerical_shaman/shaman) library) but, I have not tested it yet so a syntax error might have crept it.

Do not hesitate to contact me if you spot a problem or need further support :)
