### ISSUE TITLE
Procedure to initialize a constant to maximum precision

### ISSUE THREAD

**Issue by dgazzoni** [nestordemeure/pairArithmetic#2]
I guess this may be more of a conceptual question than one related to your implementation. I'm hoping an answer might be useful not only to myself, but to others looking to use the library -- perhaps this discussion could be added to the documentation.

Suppose I would like to load a constant as a `CompensatedNumber<double>` with as much precision as possible. This constant can be computed using MPFR, Wolfram Alpha, PARI/GP, Sage or anything else capable of arbitrary precision floats. For the sake of example, let's use π, and I'll show some code in PARI/GP with the default 38-digit precision, which should be plenty.

First, I compute a double-precision approximation to π, which calls for normalizing the mantissa to the interval [1,2) (requiring a division by 2 in this case) and subtracting the implicit integer part of 1:

```
? Pi_d = 2.0 * (1 + round((Pi/2 - 1)*2^52)/2^52)
%1 = 3.1415926535897931159979634685441851616
```

Next I compute the error:

```
? e = Pi - Pi_d
%2 = 1.2246467991473531772260471018642244504 E-16
```

Given these results, is this the correct way to initialize a `CompensatedNumber<double>` to achieve the best possible approximation to π within the available precision?

```
CompensatedNumber<double> Pi(3.141592653589793, 1.2246467991473532e-16);
```

**Comment by nestordemeure** [comment]
You have the key ideas. I would do it as follows (note that this could easily be automated):

```cpp
PI = ...; // high precision, you get this from MPFR or something else
pi_double = static_cast<double>(PI); // or any good double approximation for pi
pi_double_error = static_cast<double>(PI - pi_double); // our approximation error, encoded in double as precisely as we can

pi_compensated = CompensatedNumber<double>(pi_double, pi_double_error); // number as represented by the pair
```

**Comment by nestordemeure** [comment]
Do not hesitate to submit a PR to improve the readme if you believe this information could be more widely useful.
