### ISSUE TITLE
Add complex division operator

### ISSUE THREAD

**Issue by dgazzoni** [nestordemeure/pairArithmetic#3]
First of all, I'm so very sorry that I wasn't explicit enough in the previous issue (#1). My applications uses complex numbers, so what I actually need is division of complex numbers.

The updated README claims that complex division wouldn't be too hard to implement either. Would you be so kind as to add complex divisions as well?

Thanks in advance, and again, my apologies for not being explicit about what I actually needed.

**Comment by nestordemeure** [comment]
No problem, I suspected it might be the case but since compensated complex number division is harder (you cannot just compensate the naive algorithm), I pushed it further in the TODO list. I will try to add it shortly.

**Comment by nestordemeure** [comment]
Done!
